import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import React, { Suspense } from "react";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next.js App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme="winter">
            <body>
                <AuthProvider>
                    <NavBar />
                    <main className="p-5">
                        <Suspense fallback={<p>Loading...</p>}>
                            {children}
                        </Suspense>
                    </main>
                </AuthProvider>
                //i want add a footer here
                <footer className="bg-gray-800 text-white p-4 text-center">
                    <p>&copy; {new Date().getFullYear()} My Next.js App</p>
                    <p>
                        Built with{" "}
                        <a
                            href="https://nextjs.org"
                            className="text-blue-400 hover:underline"
                        >
                            Next.js
                        </a>
                    </p>
                </footer>
                <style jsx global>{`
                    body {
                        font-family: ${inter.style.fontFamily},
                            ${Roboto.style.fontFamily};
                    }
                `}</style>
            </body>
        </html>
    );
}
