import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import React, { Suspense } from "react";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next.js App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme="winter">
            <body>
                <AuthProvider>
                    <NavBar />
                    <main className="p-5">
                        <Suspense fallback={<p>Loading...</p>}>
                            {children}
                        </Suspense>
                    </main>
                </AuthProvider>
            </body>
        </html>
    );
}
